#!/usr/bin/env sh
bank_hash=$(./target/release/solana-ledger-tool -l config/bootstrap-validator bank-hash)

# NOTE: each developer will need to adjust the tip-program-pubkey AND the declare_id!() field
# in the anchor program based on the private key used to deploy the program on your cluster
RUST_LOG=INFO \
	NDEBUG=1 ./multinode-demo/bootstrap-validator.sh  \
  --wait-for-supermajority 0 \
  --expected-bank-hash $bank_hash \
  --validator_interface_address http://127.0.0.1:10101 \
  --rpc-pubsub-enable-block-subscription \
  --enable-rpc-transaction-history \
  --tip-program-pubkey Ek3SBXmGDvyvCGPYb98du8CNNjTomyiuc1wh7dMBw8gk
