#!/usr/bin/env sh
bank_hash=$(./target/release/solana-ledger-tool -l config/bootstrap-validator bank-hash)

# NOTE: each developer will need to adjust the tip-payment-program-pubkey and tip-distribution-program-pubkey AND
# their respective declare_id!() fields in each anchor program based on the private key used to deploy the program on your cluster.
RUST_LOG=INFO \
	NDEBUG=1 ./multinode-demo/bootstrap-validator.sh  \
  --wait-for-supermajority 0 \
  --expected-bank-hash $bank_hash \
  --block-engine-address http://127.0.0.1:1003 \
  --block-engine-auth-service-address http://127.0.0.1:1005 \
  --relayer-auth-service-address http://127.0.0.1:11226 \
  --relayer-address http://127.0.0.1:11226 \
  --rpc-pubsub-enable-block-subscription \
  --enable-rpc-transaction-history \
  --tip-payment-program-pubkey AeehMKWUfPDcuU2mnx7jyuHgr6NjyFvSxvjSnudgkQRo \
  --tip-distribution-program-pubkey APy2ShJsonjhn9ka1oa9vwEVpcspqra2gkFWx4kvpsW8 \
  --commission-bps 0 \
  --shred-receiver-address 127.0.0.1:1002 \
  --allow-private-addr \
  --trust-relayer-packets \
  --trust-block-engine-packets
