//! This module contains definitions of various types of signature verified messages.

use {
    crate::{
        certificate::Certificate, consensus_message::VoteMessage, vote::Vote,
        wire::VotePayloadToSign,
    },
    bitvec::vec::BitVec,
    solana_bls_signatures::{Signature as BLSSignature, SignatureProjective},
    std::num::NonZero,
};

/// A batch of vote or cert being sent within the node.  They were either sig verified before being
/// sent or they were generated by the node itself so do not need to be sig verified.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SigVerifiedBatch {
    /// Batch of votes.
    Votes(Vec<VoteAggregate>),
    /// Batch of certs.
    Certificates(Vec<Certificate>),
}

impl SigVerifiedBatch {
    /// Returns the length of the batch
    pub fn len(&self) -> usize {
        match self {
            Self::Votes(aggregates) => aggregates.len(),
            Self::Certificates(certs) => certs.len(),
        }
    }

    /// Returns true if the batch is empty.
    pub fn is_empty(&self) -> bool {
        match self {
            Self::Votes(aggregates) => aggregates.is_empty(),
            Self::Certificates(certs) => certs.is_empty(),
        }
    }
}

/// A batch of identical votes that have been sigverified
///
/// NOTE: the fields should not be exposed outside of the crate so that users use approved paths to
/// build it to ensure signature verification takes place.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct VoteAggregate {
    /// The type of vote in the batch.
    vote: Vote,
    /// The aggregate signature of the votes in the batch.
    signature: BLSSignature,
    /// The total stake in the batch.
    stake: NonZero<u64>,
    /// Ranks of the various validators whose votes are in the batch.
    ranks: BitVec<u8>,
}

impl VoteAggregate {
    /// Creates a sig verified vote batch from a VoteMessage.
    ///
    /// WARN: this is only public to enable handling already verified votes that are sent within
    /// the validator.  Think carefully before using this in production code.
    pub fn new_from_verified_vote(max_validators: usize, msg: VoteMessage) -> Self {
        assert!((msg.rank as usize) < max_validators);
        let mut ranks = BitVec::repeat(false, max_validators);
        ranks.set(msg.rank as usize, true);
        Self {
            vote: msg.vote,
            signature: msg.signature,
            stake: msg.stake,
            ranks,
        }
    }

    /// Creates a sig verified vote batch from a list of verified votes.
    ///
    /// WARN: this function should not be exposed outside of this crate.  This crate uses it after
    /// it has verified the votes.
    ///
    /// WARN: this function assumes that there are no duplicates in ranks_and_stakes_iter and each rank in the iter is < max_validators.
    pub fn new_from_verified_votes(
        max_validators: usize,
        vote_payload_to_sign: VotePayloadToSign,
        ranks_and_stakes_iter: impl Iterator<Item = (u16, NonZero<u64>)>,
        aggregate_signature: SignatureProjective,
    ) -> Self {
        let mut ranks = BitVec::repeat(false, max_validators);
        let mut total_stake = None;
        for (rank, stake) in ranks_and_stakes_iter {
            assert!((rank as usize) < max_validators);
            assert!(!ranks[rank as usize]);
            match total_stake {
                None => total_stake = Some(stake),
                Some(t) => total_stake = Some(t.saturating_add(stake.get())),
            }
            ranks.set(rank as usize, true);
        }
        let vote = Vote::from(vote_payload_to_sign);
        Self {
            vote,
            signature: aggregate_signature.into(),
            stake: total_stake.unwrap(),
            ranks,
        }
    }

    /// Accessor for the Vote.
    pub fn vote(&self) -> &Vote {
        &self.vote
    }

    /// Accessor for the ranks.
    pub fn ranks(&self) -> &BitVec<u8> {
        &self.ranks
    }

    /// Accessor for the signature.
    pub fn signature(&self) -> &BLSSignature {
        &self.signature
    }

    /// Accessor for the stake.
    pub fn stake(&self) -> NonZero<u64> {
        self.stake
    }

    /// Returns number of votes in the aggregate.
    pub fn num_votes(&self) -> usize {
        self.ranks.count_ones()
    }
}
