[package]
name = "jito-scheduler"
description = "Jito scheduling policy over Agave shared-memory bindings"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
agave-scheduler-bindings = { workspace = true }
agave-scheduling-utils = { workspace = true, features = ["agave-unstable-api"] }
agave-transaction-view = { workspace = true }
jito-scheduler-bindings = { path = "../jito-scheduler-bindings" }
rts-alloc = { workspace = true }
solana-pubkey = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
solana-keypair = { workspace = true }
solana-message = { workspace = true }
solana-system-transaction = { workspace = true }
solana-transaction = { workspace = true }
solana-hash = { workspace = true }
wincode = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
