[package]
name = "solana-svm-conformance"
description = "Conformance harnesses for the Solana SVM"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
workspace = "../dev-bins"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "test_exec_elf_loader"
path = "src/bin/test_exec_elf_loader.rs"
required-features = ["cli", "ffi"]

[[bin]]
name = "test_exec_vm_serialization"
path = "src/bin/test_exec_vm_serialization.rs"
required-features = ["cli", "ffi"]

[features]
default = ["cli", "ffi"]
agave-unstable-api = []
cli = ["dep:clap"]
dev-context-only-utils = []
dummy-for-ci-check = []
ffi = [
    "dep:prost",
    "dep:protosol",
    "dep:solana-compute-budget",
    "dep:solana-program-runtime",
    "dep:solana-svm",
    "dep:solana-syscalls",
    "solana-svm/conformance",
]
frozen-abi = []

[dependencies]
clap = { version = "4.5.59", features = ["derive"], optional = true }
prost = { version = "0.11", optional = true }
protosol = { version = "=10.1.0", optional = true }
solana-compute-budget = { workspace = true, optional = true }
solana-program-runtime = { workspace = true, optional = true }
solana-svm = { workspace = true, optional = true }
solana-syscalls = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true }
solana-sdk-ids = { workspace = true }

[lints]
workspace = true
