use agave_votor_messages::{certificate::Certificate, consensus_message::VoteMessage};

/// A batch of vote or cert being sent within the node.  They were either sig verified before being
/// sent or they were generated by the node itself so do not need to be sig verified.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SigVerifiedBatch {
    /// Batch of votes.
    Votes(Vec<VoteMessage>),
    /// Batch of certs.
    Certificates(Vec<Certificate>),
}

impl SigVerifiedBatch {
    /// Returns the length of the batch
    pub fn len(&self) -> usize {
        match self {
            Self::Votes(votes) => votes.len(),
            Self::Certificates(certs) => certs.len(),
        }
    }

    /// Returns true if the batch is empty.
    pub fn is_empty(&self) -> bool {
        match self {
            Self::Votes(votes) => votes.is_empty(),
            Self::Certificates(certs) => certs.is_empty(),
        }
    }
}
