name: Dependabot PR

on:
  pull_request:
    branches:
      - master

jobs:
  dependabot:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Create github app token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        run: |
          git config --global user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git config --global user.name "dependabot[bot]"
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf https://github.com/
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: update code
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          input="$PR_TITLE"

          regex='[Bb]ump (.+) from ([^ ]+) to ([^ ]+)( in .*)?'
          if [[ ! "$input" =~ $regex ]]; then
            echo "unexpected pattern"
            exit 1
          fi

          crate_name="${BASH_REMATCH[1]}"
          old_version="${BASH_REMATCH[2]}"
          new_version="${BASH_REMATCH[3]}"
          echo "crate_name: $crate_name, old_version: $old_version, new_version: $new_version"

          cargo xtask update-crate --package $crate_name --from $old_version --to $new_version

          ./scripts/cargo-for-all-lock-files.sh --ignore-exit-code -- update -p $crate_name:$old_version --precise $new_version

          ./scripts/cargo-for-all-lock-files.sh tree

      - name: push
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "✅ Nothing to update"
          else
            git add **/Cargo.toml
            git add **/Cargo.lock
            git commit -am "Update all workspaces"
            git push
          fi
