name: Downstream Project - SPL (Nightly)

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  main:
    if: github.repository_owner == 'anza-xyz'
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
    uses: ./.github/workflows/downstream-project-spl.yml
    with:
      branch: ${{ matrix.branch }}
