name: "Issue Label Actions"

on:
  issues:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write

jobs:
  action:
    runs-on: ubuntu-24.04
    steps:
      - uses: dessant/label-actions@809e0f9bc11ce08744e7ccac7cd10621d00aba2f  # v5.0.2
