name: Release

on:
  push:
    tags:
      - "*"

jobs:
  trigger-buildkite-pipeline:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v2.4.1"
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
          pipeline: "anza/agave-secondary"
          branch: "${{ github.ref_name }}"
          build_env_vars: '{"TRIGGERED_BUILDKITE_TAG": "${{ github.ref_name }}"}'
          commit: "HEAD"
          message: ":github: Triggered from a GitHub Action"

  draft-release:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ github.ref_name }}',
              name: 'Release ${{ github.ref_name }}',
              body: '🚧',
              draft: false,
              prerelease: true
            })
