name: Release

on:
  push:
    tags:
      - "*"

jobs:
  trigger-buildkite-pipeline:
    if: github.repository_owner == 'anza-xyz'
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@909fed762c73d5ae2b5d555ab910d66b3fae2670"  # v2.4.1
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
          pipeline: "anza/agave-secondary"
          branch: "${{ github.ref_name }}"
          build_env_vars: '{"TRIGGERED_BUILDKITE_TAG": "${{ github.ref_name }}"}'
          commit: "HEAD"
          message: ":github: Triggered from a GitHub Action"

  draft-release:
    if: github.repository_owner == 'anza-xyz'
    runs-on: ubuntu-24.04
    steps:
      - name: Create Release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        env:
          REF_NAME: ${{ github.ref_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.REF_NAME,
              name: `Release ${process.env.REF_NAME}`,
              body: '🚧',
              draft: false,
              prerelease: true
            })
